"""add gender column

Revision ID: 0e40b129acbd
Revises: c75fd2caf444
Create Date: 2019-08-13 16:02:07.314200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e40b129acbd'
down_revision = 'c75fd2caf444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('user', sa.Column('gender', sa.Enum('male', 'female'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
