"""empty message

Revision ID: 6512559b14a7
Revises: 8e41c1db2f3a
Create Date: 2019-08-15 12:51:53.465200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6512559b14a7'
down_revision = '8e41c1db2f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', mysql.ENUM('男', '女'), nullable=True))
    # ### end Alembic commands ###
