"""empty message

Revision ID: d86aeb0e0ef2
Revises: 6512559b14a7
Create Date: 2019-08-15 12:52:08.910200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86aeb0e0ef2'
down_revision = '6512559b14a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('男', '女', '保密'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
