"""create table user

Revision ID: 181b875cefdd
Revises: 
Create Date: 2019-08-14 14:23:12.001200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181b875cefdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
