"""add password

Revision ID: 85942d24f778
Revises: 181b875cefdd
Create Date: 2019-08-14 16:05:07.760200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85942d24f778'
down_revision = '181b875cefdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
